apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    {{ range $i, $entry := .AddressPools -}}
    - name: {{ $entry.Name }}
      protocol: {{ $entry.Protocol }}
      addresses:
      {{ range $a := $entry.Addresses -}}
      - {{ $a }}
      {{ end }}
    {{ end }}
    peers:
    {{ range $i, $entry := .Peers }}
    - peer-address: {{ $entry.Address }}
      peer-asn: {{ $entry.PeerASN }}
      my-asn: {{ $entry.ASN }}
    {{ end }}
