apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: metallbs.loadbalancer.openshift.io
spec:
  group: loadbalancer.openshift.io
  names:
    kind: MetalLB
    listKind: MetalLBList
    plural: metallbs
    singular: metallb
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: MetalLB is the Schema for the metallbs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: MetalLBSpec defines the desired state of MetalLB
          properties:
            address-pools:
              description: Address pools
              items:
                properties:
                  addresses:
                    description: A range of VIPs that metallb can use for loadbalancing.
                      Can be either a full CIDR or a range like 1.1.1.1-1.1.1.10.
                    items:
                      type: string
                    type: array
                  name:
                    description: Name of the pool
                    type: string
                  protocol:
                    description: The protocol to use for advertising VIPs. Either
                      layer2 or bgp.
                    type: string
                required:
                - addresses
                - name
                - protocol
                type: object
              type: array
            peers:
              description: Peers for BGP mode
              items:
                properties:
                  my-asn:
                    description: My ASN
                    type: string
                  peer-address:
                    description: Peer address
                    type: string
                  peer-asn:
                    description: Peer ASN
                    type: string
                required:
                - my-asn
                - peer-address
                - peer-asn
                type: object
              type: array
          required:
          - address-pools
          type: object
        status:
          description: MetalLBStatus defines the observed state of MetalLB
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
