apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: metallb-operator
  template:
    metadata:
      labels:
        name: metallb-operator
    spec:
      serviceAccountName: metallb-operator
      containers:
        - name: metallb-operator
          # Replace this with the built image name
          image: virthost.ostest.test.metalkube.org:5000/metallb-operator
          command:
          - metallb-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "metallb-operator"
